FORMAT: 1A
HOST: http://intergalacticdb.me/

# Starhub API

Starhub API is a database of a collection of characters, planets, species, etc of StarWars Universe.  


## Character Collection [/api/characters]

### List all StarWars Characters [GET]
+ Response 200 (application/json)

        [
            {
                "birth": "31.5 BBY , Kamino",
                "description": "Boba Fett was a Mandalorian warrior and bounty hunter. He was the only unaltered clone of the famed Jango Fett, created in 32 BBY as unit A0050, one of the first of many Fett replicas designed to become part of the Grand Army of the Republic, and was raised as Jango's son. Jango taught Boba much, training him to become a skilled bounty hunter as was his father-figure before him. In 22 BBY, Jango was killed at the Battle of Geonosis, which opened the Clone Wars.",
                "gender": "Male",
                "height": "1.83 meters",
                "image": "http://img2.wikia.nocookie.net/__cb20130920001614/starwars/images/5/58/BobaFettMain2.jpg",
                "name": "Boba Fett",
                "planet": "Kamino",
                "species": "Human"
            },
            {
                "birth": "200 BBY, Kashyyyk", 
                "description": "Chewbacca (or \"Chewie\", as he was known by his friends) was a legendary Wookiee from Kashyyyk and co-pilot of Han Solo's ship, the Millennium Falcon. He was the son of Attichitcuk, the husband of Mallatobuck, and the father of Lumpawaroo. Chewbacca carried with him the name of an ancient Wookiee hero, the great Bacca, first of the great chieftains of Kashyyyk, and the creator of a sword that denoted leadership among the Wookiees. This name placed Chewbacca in a noble lineage.", 
                "gender": "Male", 
                "height": "2.28 meters", 
                "image": "http://img4.wikia.nocookie.net/__cb20080815045819/starwars/images/thumb/7/73/Chewbaccaheadshot.jpg/500px-Chewbaccaheadshot.jpg", 
                "name": "Chewbacca", 
                "planet": "Kashyyyk", 
                "species": "Wookiee"
            },
            {
                "birth": "600 BBY, Nal Hutta",
                "description": "Jabba Desilijic Tiure, better known as Jabba the Hutt and often called the \"Bloated One,\" though never to his face, was one of the most notorious Hutt crime lords in the galaxy, who governed a large criminal empire located in the Outer Rim Territories from his desert palace on Tatooine. At the height of his power, Jabba was one of the most powerful crime lords in the galaxy, even having contact with Prince Xizor, the head of the Black Sun Syndicate.",
                "gender": "Hermaphrodite",
                "height": "3.9 meters long\n1.75 meters tall",
                "image": "http://img1.wikia.nocookie.net/__cb20080409144511/starwars/images/e/e5/Jabba_Boonta_Eve.jpg",
                "name": "Jabba the Hutt",
                "planet": "Nal Hutta",
                "species": "Hutt"
            }
        ]

## Character [/api/characters/{name}]
A single Character with all its details

+ Parameters
    + name (string) - name of a character

### Retrieve a Character [GET]
+ Response 200 (application/json)

    + Body
    
            {
                "birth": "200 BBY, Kashyyyk", 
                "description": "Chewbacca (or \"Chewie\", as he was known by his friends) was a legendary Wookiee from Kashyyyk and co-pilot of Han Solo's ship, the Millennium Falcon. He was the son of Attichitcuk, the husband of Mallatobuck, and the father of Lumpawaroo. Chewbacca carried with him the name of an ancient Wookiee hero, the great Bacca, first of the great chieftains of Kashyyyk, and the creator of a sword that denoted leadership among the Wookiees. This name placed Chewbacca in a noble lineage.", 
                "gender": "Male", 
                "height": "2.28 meters", 
                "image": "http://img4.wikia.nocookie.net/__cb20080815045819/starwars/images/thumb/7/73/Chewbaccaheadshot.jpg/500px-Chewbaccaheadshot.jpg", 
                "name": "Chewbacca", 
                "planet": "Kashyyyk", 
                "species": "Wookiee"
            }


## Species Collection [/api/species]

### List all StarWars Species [GET]
+ Response 200 (application/json)

        [
            
            {
                "characters": 2,
                "classification": "Mammal",
                "description": "Tall, hair covered, retractable climbing claws, long life spans",
                "image": "http://img2.wikia.nocookie.net/__cb20061128184734/starwars/images/5/57/ThreeWookieeAmigos-ROTSVD.jpg",
                "language": "Shyriiwook\nXaczik\nThykarann",
                "name": "Wookiee",
                "planet": "Kashyyyk"
            },
                
            {
                "characters": 48,
                "classification": "Mammal",
                "description": "Unknown",
                "image": "http://img3.wikia.nocookie.net/__cb20100628191857/starwars/images/5/5d/Humans-TESB30.jpg",
                "language": "Galactic Basic Standard\nOthers",
                "name": "Human",
                "planet": "Coruscant"
            },

                
            {
                "characters": 1,
                "classification": "Unknown",
                "description": "Gastropods\nHermaphrodites",
                "image": "http://img2.wikia.nocookie.net/__cb20130115030417/starwars/images/a/a7/HuttNEGAS.png",
                "language": "Huttese",
                "name": "Hutt",
                "planet": "Varl"
            }
        ]

    
## Species [/api/species/{name}]
A single Species with all its details in it

    + name (string) - name of a species

### Retrieve a species [GET]
+ Response 200 (application/json)
    + Body
    
            {
                "characters": 1,
                "classification": "Unknown",
                "description": "Gastropods\nHermaphrodites",
                "image": "http://img2.wikia.nocookie.net/__cb20130115030417/starwars/images/a/a7/HuttNEGAS.png",
                "language": "Huttese",
                "name": "Hutt",
                "planet": "Varl"
            }
    

## Planet Collection [/api/planets]

### List all planet locations [GET]
+ Response 200 (application/json)

        [
            {
                "characters": "6",
                "description": "Tatooine (pronounced/t\u00e6tu'in/; Jawaese: Tah doo Een e) was a desert world and the first planet in the binary Tatoo star system. It was part of the Arkanis sector in the Outer Rim Territories. It was inhabited by poor locals who mostly farmed moisture for a living. Other activities included used equipment retailing and scrap dealing. The planet was on the 5709-DC Shipping Lane, a spur of the Triellus Trade Route, which itself connected to the Sisar Run.",
                "image": "http://img2.wikia.nocookie.net/__cb20130226044533/starwars/images/thumb/1/18/Tatooine3.png/500px-Tatooine3.png",
                "name": "Tatooine",
                "region": "Outer Rim Territories",
                "species": "1",
                "system": "Tatoo system"
            },

            {
                "characters": "1",
                "description": "Kamino (pronounced/k\u0259'mino\u028a/), also known as the Planet of Storms, was the watery world where the Clone Army of the Galactic Republic was created, as well as the Kamino Home Fleet. It was inhabited by a race of tall, elegant beings called the Kaminoans, who kept to themselves and were known for their cloning technology. Kamino was located just south of the Rishi Maze, and was governed by the Ruling Council, headed by the Prime Minister.",
                "image": "http://img2.wikia.nocookie.net/__cb20090527045541/starwars/images/thumb/a/a9/Eaw_Kamino.jpg/500px-Eaw_Kamino.jpg",
                "name": "Kamino",
                "region": "Wild Space\nExtra-galactic",
                "species": "0",
                "system": "Kamino system"
            },
            
            {
                "characters": "2",
                "description": "Kashyyyk (see pronunciation), also known as Wookiee Planet C, Edean, G5-623, and Wookiee World, was a Mid Rim planet. It was the lush, wroshyr tree-filled home world of the Wookiees. It was a member of the Galactic Republic, endured enslavement under the Galactic Empire, and later joined the New Republic. With no axial tilt and a perfectly circular orbit, Kashyyyk experienced one continuous season. It was composed of a molten metallic core, rocky mantle, and a silicate rock crust.",
                "image": "http://img3.wikia.nocookie.net/__cb20130202022903/starwars/images/e/e8/Can-cell_kashyyyk.png",
                "name": "Kashyyyk",
                "region": "Mid Rim",
                "species": "1",
                "system": "Kashyyyk system"
            }
        ]
        

## Planet [/api/planets/{name}]
A single planet with all its details in it

+ Parameters
    + name (string) - name of a planet


### Retrieve a planet [GET]
+ Response 200 (application/json)

    + Body
    
            {
                "characters": "2",
                "description": "Kashyyyk (see pronunciation), also known as Wookiee Planet C, Edean, G5-623, and Wookiee World, was a Mid Rim planet. It was the lush, wroshyr tree-filled home world of the Wookiees. It was a member of the Galactic Republic, endured enslavement under the Galactic Empire, and later joined the New Republic. With no axial tilt and a perfectly circular orbit, Kashyyyk experienced one continuous season. It was composed of a molten metallic core, rocky mantle, and a silicate rock crust.",
                "image": "http://img3.wikia.nocookie.net/__cb20130202022903/starwars/images/e/e8/Can-cell_kashyyyk.png",
                "name": "Kashyyyk",
                "region": "Mid Rim",
                "species": "1",
                "system": "Kashyyyk system"
            }
            
